name: Latest blog posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in feed posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://chris.bur.gs/feed/feed.xml"
          commit_message: "🤖 feed items update from workflow"
